In [1]:
def loadExData():
    # 原矩阵
    return[[0, -1.6, 0.6],
           [0, 1.2, 0.8],
           [0, 0, 0],
           [0, 0, 0]]

In [2]:
 # 对矩阵进行SVD分解(用python实现SVD)
Data = loadExData()
print('Data:', Data)

Data: [[0, -1.6, 0.6], [0, 1.2, 0.8], [0, 0, 0], [0, 0, 0]]


In [3]:
from numpy import linalg as la
from numpy import *

In [4]:
U,Sigma,VT = linalg.svd(Data)

In [5]:
U

array([[ 0.8,  0.6,  0. ,  0. ],
       [-0.6,  0.8,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [6]:
Sigma

array([2., 1., 0.])

In [7]:
VT

array([[ 0.00000000e+00, -1.00000000e+00,  5.55111512e-17],
       [ 0.00000000e+00,  1.75768804e-17,  1.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [8]:
print('U:', U)
print('Sigma', Sigma)
print('VT:', VT)
print('VT:', VT.T)

U: [[ 0.8  0.6  0.   0. ]
 [-0.6  0.8  0.   0. ]
 [ 0.   0.   1.   0. ]
 [ 0.   0.   0.   1. ]]
Sigma [2. 1. 0.]
VT: [[ 0.00000000e+00 -1.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00  1.75768804e-17  1.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00]]
VT: [[ 0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [-1.00000000e+00  1.75768804e-17  0.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00  0.00000000e+00]]


In [9]:
 # 重构一个3x3的矩阵Sig3
Sig3 = mat([[Sigma[0], 0, 0], [0, Sigma[1], 0], [0, 0, Sigma[2]]])
print(U[:, :3] * Sig3 * VT[:3, :])

[[ 0.  -1.6  0.6]
 [ 0.   1.2  0.8]
 [ 0.   0.   0. ]
 [ 0.   0.   0. ]]


In [10]:
# 相似度计算，假定inA和inB 都是列向量
# 基于欧氏距离,norm是求范数，默认是二范数
def ecludSim(inA, inB):
    return 1.0/(1.0 + la.norm(inA - inB))

In [11]:
# 计算欧氏距离
myMat = mat(loadExData())

In [12]:
myMat

matrix([[ 0. , -1.6,  0.6],
        [ 0. ,  1.2,  0.8],
        [ 0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ]])

In [13]:
print(ecludSim(myMat[:, 0], myMat[:, 4]))
print(ecludSim(myMat[:, 0], myMat[:, 0]))

IndexError: index 4 is out of bounds for axis 1 with size 3

In [14]:
def loadExData():
    """
    # 推荐引擎示例矩阵
    return[[4, 4, 0, 2, 2],
           [4, 0, 0, 3, 3],
           [4, 0, 0, 1, 1],
           [1, 1, 1, 2, 0],
           [2, 2, 2, 0, 0],
           [1, 1, 1, 0, 0],
           [5, 5, 5, 0, 0]]
    """
    # 原矩阵
    return[[1, 1, 1, 0, 0],
           [2, 2, 2, 0, 0],
           [1, 1, 1, 0, 0],
           [5, 5, 5, 0, 0],
           [1, 1, 0, 2, 2],
           [0, 0, 0, 3, 3],
           [0, 0, 0, 1, 1]]

    # 原矩阵
#     return[[0, -1.6, 0.6],
#            [0, 1.2, 0.8],
#            [0, 0, 0],
#            [0, 0, 0]]

In [15]:
# 计算欧氏距离
myMat = mat(loadExData())

In [16]:
myMat

matrix([[1, 1, 1, 0, 0],
        [2, 2, 2, 0, 0],
        [1, 1, 1, 0, 0],
        [5, 5, 5, 0, 0],
        [1, 1, 0, 2, 2],
        [0, 0, 0, 3, 3],
        [0, 0, 0, 1, 1]])

In [17]:
print(ecludSim(myMat[:, 0], myMat[:, 4]))
print(ecludSim(myMat[:, 0], myMat[:, 0]))

0.13367660240019172
1.0


In [18]:
# 计算余弦相似度，如果夹角为90度，相似度为0；如果两个向量的方向相同，相似度为1.0
def cosSim(inA, inB):
    num = float(inA.T*inB)
    denom = la.norm(inA)*la.norm(inB)
    return 0.5 + 0.5*(num/denom)

In [20]:
  # 计算余弦相似度
print(cosSim(myMat[:, 0], myMat[:, 4]))
print(cosSim(myMat[:, 0], myMat[:, 0]))

0.5472455591261534
0.9999999999999999


In [22]:

# pearsSim()函数会检查是否存在3个或更多的点。
# corrcoef直接计算皮尔逊相关系数，范围[-1, 1]，归一化后[0, 1]
def pearsSim(inA, inB):
    # 如果不存在，该函数返回1.0，此时两个向量完全相关。
    if len(inA) < 3:
        return 1.0
    return 0.5 + 0.5 * corrcoef(inA, inB, rowvar=0)[0][1]
# 计算皮尔逊相关系数
print(pearsSim(myMat[:, 0], myMat[:, 4]))
print(pearsSim(myMat[:, 0], myMat[:, 0]))

0.23768619407595815
1.0


In [23]:
def loadExData3():
    # 利用SVD提高推荐效果，菜肴矩阵
    return[[2, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5],
           [0, 0, 0, 0, 0, 0, 0, 1, 0, 4, 0],
           [3, 3, 4, 0, 3, 0, 0, 2, 2, 0, 0],
           [5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 5, 0, 0, 5, 0],
           [4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 5],
           [0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 4],
           [0, 0, 0, 0, 0, 0, 5, 0, 0, 5, 0],
           [0, 0, 0, 3, 0, 0, 0, 0, 4, 5, 0],
           [1, 1, 2, 1, 1, 2, 1, 0, 4, 5, 0]]


def loadExData2():
    # 书上代码给的示例矩阵
    return[[0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 5],
           [0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 3],
           [0, 0, 0, 0, 4, 0, 0, 1, 0, 4, 0],
           [3, 3, 4, 0, 0, 0, 0, 2, 2, 0, 0],
           [5, 4, 5, 0, 0, 0, 0, 5, 5, 0, 0],
           [0, 0, 0, 0, 5, 0, 1, 0, 0, 5, 0],
           [4, 3, 4, 0, 0, 0, 0, 5, 5, 0, 1],
           [0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 4],
           [0, 0, 0, 2, 0, 2, 5, 0, 0, 1, 2],
           [0, 0, 0, 0, 5, 0, 0, 0, 0, 4, 0],
           [1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0]]