In [1]:
from numpy import *
import operator
import os
from collections import Counter

In [25]:
# knn 就是求测试样本与训练样本的关联度，距离最近的最有可能是这个类别,排序并返回出现最多的那个类型

In [3]:
def createDataSet():
    group = array([[1.0, 1.1], [1.0, 1.0], [0, 0], [0, 0.1]])
    labels = ['A', 'A', 'B', 'B']
    return group, labels

In [4]:
inx = (1,2)

In [5]:
tile(inx,(3,2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2]])

In [6]:
# tile(输入,(行数，复制的次数))

In [8]:
group, labels = createDataSet()

In [9]:
group

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])

In [10]:
group.shape[0]

4

In [12]:
diffMat = tile(inx,(4,1))-group

In [13]:
diffMat

array([[0. , 0.9],
       [0. , 1. ],
       [1. , 2. ],
       [1. , 1.9]])

In [14]:
sqDiffMat = diffMat ** 2

In [15]:
sqDiffMat

array([[0.  , 0.81],
       [0.  , 1.  ],
       [1.  , 4.  ],
       [1.  , 3.61]])

In [20]:
sqDistances = sqDiffMat.sum(axis=1)

In [17]:
sqDistances

array([0.81, 1.  , 5.  , 4.61])

In [18]:
# axis =1 代表在行的维度上对列进行操作运算

In [21]:
distances = sqDistances ** 0.5

In [22]:
distances

array([0.9       , 1.        , 2.23606798, 2.14709106])

In [23]:
sortedDistIndicies = distances.argsort()

In [24]:
sortedDistIndicies

array([0, 1, 3, 2])